### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by churoc** [FreeformRobotics/MISO_connection#1]
Thank you for your open-source code. It is indeed an excellent job. However, I ran into a few issues while trying to reproduce the results from the article.：

Although there are corresponding generation files for all matrix data, I couldn't find a generation file for './data/results/CNL_Pairing/', like  in 19th line of 'EXP_Paring.py'.

Moreover, while having a comparison between `human_cnl` and `human_con` inside 'example_human/draw_final_human.py', CNL_Pairing package is missing in the 7th line of ‘CNL_CON.py’, hence I'm unable to generate the 'human_cnl.txt' .

**Comment by haoboluo** [comment]
Really appreciate your suggestions and the issues you found with our code!  Also, I'm sorry that I haven't replied to you in time.

The CNL_Pairing.py file has indeed not been committed successfully. It has now been committed, as well as the corresponding run_CNL.py file.

1. After running the run_CNL.py file, the results should be generated at the corresponding location './data/results/CNL_Pairing/' which is the location in 19th line of 'EXP_Paring.py' as you said above. 

2. The CNL_Pairing.py is exactly the 'CNL_Pairing' in the 7th line of ‘CNL_CON.py’. Please download the CNL_Pairing.py file to the IM folder for this bug. 

[https://github.com/FreeformRobotics/MISO_connection/blob/main/IM/CNL_Pairing.py](url)
[https://github.com/FreeformRobotics/MISO_connection/blob/main/IM/run_CNL.py](url)

Thanks again!

**Comment by churoc** [comment]
Thank you for your reply!
